# Generated by Django 3.2.15 on 2023-02-09 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_auto_20230202_2345'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='wechatID',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
