# Generated by Django 4.1.5 on 2023-02-08 18:22

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_tape'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=128)),
                ('initTime', models.DateTimeField(auto_now_add=True)),
                ('lastTime', models.DateTimeField(auto_now_add=True)),
                ('content', mdeditor.fields.MDTextField()),
            ],
        ),
    ]
